title: <p align="center"> Ariya Sontrapornpol </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ariya-sontrapornpol/">LinkedIn</a> |
  <a href="https://www.youtube.com/@JomEngineer">YouTube</a> |
  <a href="https://github.com/jomariya23156">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Machine Learning Engineer at Perceptra, MedTech startup based in Thailand.
  <br><br>
  I'm enthusiastically pursuing more knowledge in MLOps, Deep Learning, and Computer Vision. I deeply believe one day, these technologies will shape our world and create the new world that we couldn't imagine of.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID
