title: <p align="center"> Ariya Sontrapornpol </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ariya-sontrapornpol/">LinkedIn</a> |
  <a href="https://www.youtube.com/@JomEngineer">YouTube</a> |
  <a href="https://github.com/jomariya23156">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Machine Learning Engineer at Perceptra, a MedTech startup based in Thailand. I love turning ideas into products that have a positive impact on the world. :)
  <br><br>
  email - jomariya23156@gmail.com
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID
